;({
  mode: 'dynamic',
  whiteboard: true,
  title: 'Dérivation',
  data: [
    {
      type: 'Differentiate',
      params: {
        Expr: [
          // Products
          'x^2 \\ln x',
          'e^x \\sin x',
          'x^{\\frac{3}{2}} \\ln x',
          '\\sqrt{x} e^x',
          '\\ln(x) \\cos(x)',
          'x \\tan(x)',
          '\\arctan(x) \\ln(x)',
          'x^2 \\arcsin(x)',
          '\\ln(x) \\sqrt(x)',
          '\\sqrt[3]{x} \\ln x',
          'x^3 e^x',
          '3^x \\ln x',
          'x^{\\frac{2}{3}} \\cos x',
          '\\sqrt{x} \\ln x',
          // Quotients
          '\\frac{x^2}{\\ln x}',
          '\\frac{e^x}{x}',
          '\\frac{\\sin x}{x^2}',
          '\\frac{1}{\\ln x}',
          '\\frac{1}{x^2 + \\ln x}',
          '\\frac{\\tan x}{x}',
          '\\frac{x^2}{\\arcsin x}',
          '\\frac{e^x}{\\ln x}',
          '\\frac{3^x}{\\ln x}',
          '\\frac{x^2}{e^x}',
          '\\frac{\\cos x}{x}',
          '\\frac{e^x}{\\sqrt{x}}',
          // Composition
          '\\sin(\\ln x)',
          '\\ln(\\sqrt{x + 1})',
          'e^{x^3}',
          '\\arcsin(\\sqrt{x})',
          '\\ln(\\cos x)',
          '\\tan(e^x)',
          '\\ln(\\ln x)',
          '\\frac{1}{x \\ln x}',
          'e^{\\arctan x}',
          '\\ln(\\sin(x))',
          '\\sqrt{e^x + 1}',
          'e^{\\sin x}',
          '\\arctan(\\ln x)',
          '\\ln(x^2 + 1)',
          'e^{x^2}',
          '\\ln(2x)',
          '\\sqrt{e^x + 2}',
          '\\ln(\\sin(x^2))',
          '\\log_3(x^2 + 1)',
          '\\arcsin(\\sqrt{x})',
          '\\sqrt[3]{\\ln x}',
          'e^{\\tan x}',
          '\\log_5(\\cos x)',
          '\\sqrt[4]{e^{x^2} + 1}',
          'e^{\\arccos x}',
          // A bit of everything
          '\\frac{x^3 \\ln(x)}{\\sqrt{x^2 + 1}}',
          'e^x \\sin(\\ln(x))',
          '\\frac{\\tan(\\ln(x))}{x^2}',
          '\\arctan(x) e^{x^2}',
          '\\frac{x^3}{e^{\\sin x}}',
          '\\ln(x^2 + \\cos x)',
          '\\frac{\\sqrt{x}}{\\ln(\\sin(x))}',
          '\\arccos(\\sqrt{x}) \\ln(x^2)',
          '\\frac{ e^{\\arcsin x} }{ \\ln(x + 2) }',
        ],
      },
    },
  ],
}) satisfies import('~/components/ExerciseSequence').ExerciseProps
