name: Lint
on:
  - push
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - run: pip install black
      - run: black --check symapi
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Check formatting with Prettier
        run: npx prettier --check src/ "content/**/*.yaml"
