name: Unit tests
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    needs: prettier
    steps:
      - uses: actions/checkout@v5
      - run: docker compose -f docker-compose.test.yaml run --rm web_tests
      - run: docker compose -f docker-compose.test.yaml run --rm symapi pytest
