name: Tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
          npm install
      - name: Run unit tests
        run: |
          nohup bash -c "poetry run fastapi run symapi &"
          until curl -s http://localhost:8000/graphql; do sleep 1; done
          npx graphql-codegen
          poetry run pytest
          npx vitest run
