name: Tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
      - name: Run SymAPI
        run: RUNNER_TRACKING_ID="" && (poetry run fastapi dev symapi &)
      - name: Run tests
        run: |
          poetry run pytest
      - name: GraphQL codegen
        run: |
          npm install
          npx graphql-codegen
      - name: Run front-end unit tests
        run: |
          npx vitest run
